app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required


class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, flash, Markup, url_for, abort
from flask.ext.login import login_required, current_user
from . import main
from app.shared.models.data import Data
from app.shared.models.sensor import Sensor
from app.shared.models.notebook import Notebook
from app.shared.models.user import User
from app.shared.models.pod import Pod
from app.shared.models.message import Message
from bson.objectid import ObjectId

from mongoengine import Q


NBK_PER_PAGE = 12
PODS_PER_PAGE = 12


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/pods')
@main.route('/pods/<int:page>')
@login_required
def pods(page=1):
    if current_user.is_administrator():
        with_obs_owned = None
    else:
        with_obs_owned = Q(observations__gt=0) & Q(owner=current_user.get_id())
    pods = Pod.objects(
        with_obs_owned
    ).order_by('-last').only(
        'name',
        'owner',
        'mode',
        'last',
        'pod_id'
    ).paginate(
        page=page, per_page=PODS_PER_PAGE
    )
    return render_template(
        'main/pod_list.html',
        pods=pods
    )


@main.route('/notebooks')
@main.route('/notebooks/<int:page>')
@login_required
def notebooks(page=1):
    with_obs_owned = Q(observations__gt=0) & Q(owner=current_user.get_id())
    notebooks = Notebook.objects(
        with_obs_owned
    ).order_by('-last').only(
        'name',
        'voltage',
        'last',
        'observations',
        'owner',
        'public',
    ).paginate(page=page, per_page=NBK_PER_PAGE)
    unconfirmed_owned = Q(confirmed=False) & Q(owner=current_user.get_id())
    unconfirmed_notebooks = Notebook.objects(
        unconfirmed_owned
    ).order_by('-last').only(
        'name',
        'voltage',
        'last',
        'observations',
        'owner',
        'public',
    )
    for notebook in unconfirmed_notebooks:
        url = url_for('main.notebook_info', _id=notebook.get_id())
        message = Markup(
            "Your new notebook, <a href=%s>%s</a> needs to be confirmed."
            % (url, notebook.name)
        )
        flash(message, 'warning')
    return render_template(
        'user_notebook_list.html',
        title="%s's Notebooks" %
        current_user.username if 'username' in dir(current_user) else 'Guest',
        current_time=datetime.utcnow(),
        notebooks=notebooks,
        new_notebooks=''
    )


@main.route('/public')
@main.route('/public/<int:page>')
@login_required
def public(page=1):
    with_obs_public = Q(observations__gt=0) & Q(public=True)
    notebooks = Notebook.objects(
        with_obs_public
    ).order_by('-last').only(
        'name',
        'voltage',
        'last',
        'observations',
        'owner',
        'public'
    ).paginate(page=page, per_page=NBK_PER_PAGE)
    return render_template(
        'public_notebook_list.html',
        title="Public Notebooks",
        current_time=datetime.utcnow(),
        notebooks=notebooks
    )


@main.route('/user/<username>')
@login_required
def user(username):
    # Don't show user information to anyone but the user and the admin:
    if not current_user.username == username and \
            not current_user.role == 'admin':
        abort(404)
    else:
        user = User.objects(username=username).first()
    if user is None:
        abort(404)
    notebooks = Notebook.objects(owner=user)
    pods = Pod.objects(owner=user)
    data = Data.objects(owner=user)
    return render_template(
        'user.html',
        user=user,
        pods=pods,
        notebooks=notebooks,
        data=data
    )


@main.route('/pod/<_id>')
@login_required
def pod_info(_id):
    pod = None
    if ObjectId.is_valid(_id):
        pod = Pod.objects(id=_id).first()
    else:
        try:
            pod = Pod.objects(pod_id=_id).first()
        except:
            try:
                pod = Pod.objects(name=_id).first()
            except:
                pass
    if not pod:
        abort(404)
    # Only let pod owners or administrators look at pods:
    if not pod.owner.username == current_user.username and \
            not current_user.role == 'admin':
        abort(403)
    if current_user.role == 'admin':
        message_list = Message.objects(
            pod=pod
        ).limit(100).order_by('-time_stamp')
    else:
        message_list = None
    notebooks = Notebook.objects(pod=pod).order_by('-last')
    return render_template(
        'main/pod_info.html',
        current_time=datetime.utcnow(),
        pod=pod,
        message_list=message_list,
        notebooks=notebooks
    )


@main.route('/notebook/<_id>')
@login_required
def notebook_info(_id):
    notebook = Notebook.objects(
        id=_id
    ).first()
    # Check if this notebook is public. If it is, then anyone can see it.
    if notebook.public is False:
        # Only let notebook owners or administrators look at this notebook:
        if not notebook.owner == current_user and \
                not current_user.role == 'admin':
            abort(404)
    # Should really do this as an AJAX:
    # try:
    #    notebook.xls()
    #    xlsx = True
    # except:
    #    xlsx = False
    xlsx = False
    data = Data.objects(
        notebook=notebook
    ).first()
    sensors = Sensor.objects(
        sid__in=notebook.sids
    )
    current_data = {}
    for sensor in sensors:
        current_value = Data.objects(
            notebook=notebook,
            sensor=sensor).order_by('-time_stamp').first()
        if current_value:
            current_data[sensor.get_id()] = current_value.value
        else:
            current_data[sensor.get_id()] = None
    if not data:
        flash('Waiting for initial data transmission', 'warning')
    return render_template(
        'notebook_info.html',
        current_time=datetime.utcnow(),
        notebook=notebook,
        # data=data,  # No need to return data, because AJAX.
        sensors=sensors,
        current_data=current_data,
        xlsx=xlsx
    )


@main.route('/map')
@login_required
def map():
    notebooks = Notebook.objects(observations__gt=10).order_by('-last').only(
        'name',
        'location',
        'nbk_id',
        'last'
    )
    return render_template(
        'map.html',
        notebooks=notebooks
    )


@main.context_processor
def helper_functions():

    def format_price(amount, currency=u'$'):
        return u'{1}{0:.2f}'.format(amount, currency)

    def label_voltage(voltage):
        if voltage is None:
            return 'info'
        if voltage > 3.8:
            return 'success'
        if voltage > 3.6:
            return 'warning'
        return 'danger'

    def map_marker(last=None):
        import datetime
        # Active notebooks have sent data in the past week
        if last > datetime.datetime.now() - datetime.timedelta(days=7):
            return 'activeMarker'
        else:
            return 'inactiveMarker'

    def data_renderer(variable_name=None):
        if not variable_name:
            return 'line'
        if 'Counts' in variable_name:
            return 'bar'
        else:
            return 'line'

    return dict(
        format_price=format_price,
        label_voltage=label_voltage,
        map_marker=map_marker,
        data_renderer=data_renderer
    )

app/templates/main/message_list.html
{% extends "base.html" %}

{% block title %} PulsePod - Messages [ADMIN ONLY]{% endblock %}

{% from 'macros/paginate.html' import render_pager as pager %}

{% block page_content %}
<div class="page-header">
<h2>PulsePod Messages</h2>
</div>
<div class="messages">
    {% include 'main/message_list_items.html' %}
    {{ pager(messages, 'main.messages') }}
</div>
{% endblock %}

app/templates/main/message_list_items.html
{% for message in messages.items %}
<div class="notebook">
    <div class="notebook-content">
        <h4>
            Message: <a href="{{ url_for('main.message_info', _id=message.get_id() ) }}">
                 {{ message.message_content|truncate(60, true) }}
            </a>
            <br>
            <small>
                <span class="badge">{{ message.type }}</span>
            </small>
            <small>
                <span class="badge">{{ message.source}}</span>
            </small>
            <small>
            {% if message.status == 'posted' %}
                <span id="msg_queued" class="label label-success">Posted</span>
            {% elif message.status  == 'invalid' %}
                <span id="msg_invalid" class="label label-error">Invalid</span>
            {% elif message.status == 'queued' %}
                <span id="msg_queued" class="label label-warning">Queued</span>
            {% elif message.status == 'unknown' %}
                <span id="msg_unknown" class="label label-default">Unknown</span>
            {% endif %}
            </small>
        </h4>
            <span>
            {% if message.time_stamp %}
                &nbsp;Recieved {{ moment(message.time_stamp).fromNow(refresh=True) }}
            {% endif %}
            </span>
    </div>
</div>
{% endfor %}

app/templates/main/notebook_list_tiles.html
<div class="container">
{% for notebook in notebooks %}
    {%if loop.index0%4 == 0 %}
        {%if loop.index0==0 %}
           <div class="row">
        {% else %}
            </div><div class="row">
        {% endif %}
    {% endif %}
    <div id="{{notebook.get_id()}}" class="col-sm-3">
        <h4>
            <a href="{{ url_for('main.notebook_info', _id=notebook.get_id() ) }}">
                {{ notebook.name }}
            </a>
            <br>
            <small>
                <span class="badge">{{ notebook.observations }}</span>
            </small>
            <small>
            <span class="label label-{{ label_voltage(notebook.voltage) }}"> 
                <span class="glyphicon glyphicon-flash"></span>
                &nbsp;{{ notebook.voltage|round(1)|replace('None', 'unknown') }}
            </span>&nbsp;
            {% if notebook.public %}
                <span id="nbk_public" class="label label-success">Public</span>
            {% else %}
                <span id="nbk_public" class="label label-warning">Private</span>
            {% endif %}
            {% if current_user.is_administrator() %}
                <span id="owner" class="label label-default">{{ notebook.owner.username }}</span>
            {% endif %}
            </small>
        </h4>
            <span>
            {% if notebook.last %}
                &nbsp;Last updated {{ moment(notebook.last).fromNow(refresh=True) }}
            {% else %}
                &nbsp;Waiting for first update
            {% endif %}
            </span>
            {% if notebook.observations < 20 and not notebook.pod.current_notebook.get_id() == notebook.get_id() %}
                <br><a href="#" id="deleteButton" onclick="delete_notebook('{{notebook.get_id()}}')" class="btn btn-right btn-default btn-large btn-danger">Delete</a>
            {% endif %}
            {% if notebook.observations >= 20 and not notebook.pod.current_notebook.get_id() == notebook.get_id() %}
            <br><a href="#" id="mergeButton" onclick="merge_notebook('{{notebook.get_id()}}')" class="btn btn-right btn-default btn-small btn-warning">Merge to Current</a>
            {% endif %}
    </div>
    {%if loop.last == True %}
        </div>
    {% endif %}
{% endfor %}
</div>

app/templates/main/notebook_list_tiles_pager.html
<div class="container">
{% for notebook in notebooks.items %}
    {%if loop.index0%4 == 0 %}
        {%if loop.index0==0 %}
           <div class="row">
        {% else %}
            </div><div class="row">
        {% endif %}
    {% endif %}
    <div class="col-sm-3">
        <h4>
            <a href="{{ url_for('main.notebook_info', _id=notebook.get_id() ) }}">
                {{ notebook.name }}
            </a>
            <br>
            <small>
                <span class="badge">{{ notebook.observations }}</span>
            </small>
            <small>
            <span class="label label-{{ label_voltage(notebook.voltage) }}"> 
                <span class="glyphicon glyphicon-flash"></span>
                &nbsp;{{ notebook.voltage|round(1)|replace('None', 'unknown') }}
            </span>&nbsp;
            {% if notebook.public %}
                <span id="nbk_public" class="label label-success">Public</span>
            {% else %}
                <span id="nbk_public" class="label label-warning">Private</span>
            {% endif %}
            {% if current_user.is_administrator() %}
                <span id="owner" class="label label-default">{{ notebook.owner.username }}
            {% endif %}
            </small>
        </h4>
            <span>
            {% if notebook.last %}
                &nbsp;Last updated {{ moment(notebook.last).fromNow(refresh=True) }}
            {% else %}
                &nbsp;Waiting for first update
            {% endif %}
            </span>
    </div>
    {%if loop.last == True %}
        </div>
    {% endif %}
{% endfor %}
</div>

app/templates/main/pod_info.html
{% extends "base.html" %}

{% block title %} PulsePod - {{pod.name}}{% endblock %}

{% block head %}
    {{ super() }}
    <link href="//cdn.datatables.net/1.10.0/css/jquery.dataTables.css" rel="stylesheet">
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>
    {%if current_user.is_administrator() %}
    <script src="{{ url_for('static', filename='js/admin/message_list.js') }}"></script>
    {% endif %}
    <script src="{{ url_for('static', filename='js/notebook_list.js')}}"></script>
{% endblock %}


{% block page_content %}
<meta name="csrf-token" content="{{ csrf_token() }}">
{%if current_user.is_administrator() %}
<meta name="message_count" content="{{ message_list|count }}">
{% endif %}

<h2>{{pod.name}} <span class="badge">#{{ pod.pod_id }}</span></h2>
<div class="well well-lg">
This pod is currently in {{pod.mode}} mode and is writing to <a href="{{url_for('main.notebook_info',_id=pod.current_notebook.get_id())}}">{{pod.current_notebook.name}}</a>. Its most recent message was sent on {{ moment(pod.last).format('LLL') }}
</div>
{%if current_user.is_administrator() %}
Current Owner of {{pod.name}}:
<form class="form-inline" role="form">
    <div class="form-group">
        <select class="form-control">
        <option>{{pod.owner.username}}</option>
        <option>the</option>
        <option>owner</option>
        </select>
        <button type="submit" class="btn btn-primary disabled">Change Owner</button>
    </div>
</form>
{% endif %}
<div>
Previously, {{pod.name}} has written to the following notebooks:
</div>
<div class="notebooks">
    {% include 'main/notebook_list_tiles.html' %}
</div>

<div>
{%if current_user.is_administrator() %}
<div>
Recently, {{pod.name}} has sent the following messages:
    {% include '/admin/message_table.html' %}
</div>
{% endif %}


{% endblock %}

app/templates/main/pod_list.html
{% extends "base.html" %}

{% block title %} PulsePod - Pods [ADMIN ONLY]{% endblock %}

{% from 'macros/paginate.html' import render_pager as pager %}

{% block page_content %}
<div class="page-header">
<h2>PulsePod Pods</h2>
</div>
<div class="pods">
    {% include 'main/pod_list_tiles.html' %}
    {{ pager(pods, 'main.pods') }}
</div>
{% endblock %}

app/templates/main/pod_list_items.html
{% for pod in pods.items %}
<div class="notebook">
    <div class="notebook-content">
        <h4>
            <a href="{{ url_for('main.pod_info', _id=pod.get_id() ) }}">
                 {{ pod.name }}  <span class="badge">#{{ pod.pod_id }}</span>
            </a>
            <br>
            <small>
                <span class="badge">{{ pod.observations }}</span>
            </small>
            <small>
                <span class="badge">{{ pod.owner.username }}</span>
            </small>
            <small>
            {% if pod.status == 'normal' %}
                <span id="pod_normal" class="label label-success">Normal</span>
            {% elif pod.status  == 'inactive' %}
                <span id="pod_inactive" class="label label-error">Inactive</span>
            {% elif pod.status == 'teenager' %}
                <span id="pod_teenager" class="label label-warning">Teenager</span>
            {% elif pod.status == 'asleep' %}
                <span id="pod_asleep" class="label label-default">Asleep</span>
            {% endif %}
            </small>
        </h4>
            <span>
            {% if pod.last %}
                &nbsp;Last heard from {{ moment(pod.last).fromNow(refresh=True) }}
            {% endif %}
            </span>
    </div>
</div>
{% endfor %}

app/templates/main/pod_list_tiles.html
<div class="container">
{% for pod in pods.items %}
    {%if loop.index0%4 == 0 %}
        {%if loop.index0==0 %}
           <div class="row">
        {% else %}
            </div><div class="row">
        {% endif %}
    {% endif %}
    <div class="col-sm-3">
        <h4>
            <a href="{{ url_for('main.pod_info', _id=pod.get_id() ) }}">
                 {{ pod.name }} <span class="badge">#{{ pod.pod_id }}</span>
            </a>
            <br>
            <small>
                <span class="badge">{{ pod.owner.username }}</span>
            </small>
            <small>
            {% if pod.status == 'normal' %}
                <span id="pod_normal" class="label label-success">Normal</span>
            {% elif pod.status  == 'inactive' %}
                <span id="pod_inactive" class="label label-error">Inactive</span>
            {% elif pod.status == 'teenager' %}
                <span id="pod_teenager" class="label label-warning">Teenager</span>
            {% elif pod.status == 'asleep' %}
                <span id="pod_asleep" class="label label-default">Asleep</span>
            {% endif %}
            </small>
        </h4>
        <span>
        {% if pod.last %}
            &nbsp;Last heard from {{ moment(pod.last).fromNow(refresh=True) }}
        {% endif %}
        </span>
    </div>
    {%if loop.last == True %}
        </div>
    {% endif %}
{% endfor %}
</div>